version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: qwwekf/kittygram_backend:latest  # Используйте ваш DockerHub username
    container_name: backend
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi"

  frontend:
    image: qwwekf/kittygram_frontend:latest  # Используйте ваш DockerHub username
    container_name: frontend
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/
    depends_on:
      - backend

  gateway:
    image: qwwekf/kittygram_gateway:latest  # Используйте ваш DockerHub username
    container_name: gateway
    volumes:
      - static:/static
      - media:/media
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always