services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - static:/app/build/static
    restart: always

  gateway:
    build: ./nginx
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media: