server {
    listen 80;
    client_max_body_size 20M;
    client_body_timeout 120s;
    
    # Куда отправлять запросы к API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Куда отправлять запросы к админке
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Отдаем картинки и файлы
    location /media/ {
        alias /media/;
    }
    
    # Отдаем стили и скрипты
    location /static/ {
        alias /static/;
    }
    
    # Всё остальное - на фронтенд
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}